[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0"
crossbeam-channel = "0"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0", features = ["sqlite", "runtime-tokio-native-tls"] }
